language: bash

before_script:
    - git clone https://github.com/icasimpan/shcf.git
    - ./shcf/init_env.sh
    - shcf_cli new hello_world
    - echo "greeter() { echo 'Hello World' }" > $SHCF_PLATFORM_ROOT/projects/hello_world/lib/greeter.bash.inc
    - sed -i 's/rename_function1/greeter/g' $SHCF_PLATFORM_ROOT/projects/hello_world/bin/hello_world
    - sed -i 's/rename_function/d' $SHCF_PLATFORM_ROOT/projects/hello_world/bin/hello_world
    - echo "greeter >> $SHCF_PLATFORM_ROOT/projects/hello_world/bin/hello_world

script:
    - ./$SHCF_PLATFORM_ROOT/projects/hello_world/bin/hello_world
