language: bash

before_script:
    - git clone https://github.com/icasimpan/shcf.git
    ## Initialize 'shcf'
    - cd /home/travis/build/icasimpan/shcf/shcf/core/bin; ./shcf_cli init
    - shcf_cli new hello_world
    ## Now, use 'shcf_cli lib' to create the function greeter()
    - shcf_cli lib hello_world greeter
    - sed -i '/function/d' /home/travis/build/icasimpan/shcf/shcf/projects/hello_world/lib/greeter.bash.inc
    - sed -i "s/.*END.*/echo 'Hello World\!'; \}" /home/travis/build/icasimpan/shcf/shcf/projects/hello_world/lib/greeter.bash.inc
    ## Insert greeter() into bin/hello_world
    - sed -i 's/rename_function1/greeter/g' /home/travis/build/icasimpan/shcf/shcf/projects/hello_world/bin/hello_world
    - sed -i '/rename_function/d' /home/travis/build/icasimpan/shcf/shcf/projects/hello_world/bin/hello_world
    - echo "greeter" >> /home/travis/build/icasimpan/shcf/shcf/projects/hello_world/bin/hello_world

script:
    - bash /home/travis/build/icasimpan/shcf/shcf/projects/hello_world/bin/hello_world
